apiVersion: v1
kind: Service
metadata:
  name: fttx-monolith-redis
spec:
  clusterIP: None
  ports:
    - name: redis-server
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: fttx-monolith-redis
