apiVersion: apps/v1
kind: Deployment
metadata:
  name: fttx-monolith-web
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - tkk-vm-st-it-k8s-w-1
                      - tkk-vm-st-it-k8s-w-2
                      - tkk-vm-st-it-k8s-w-3
